name: Check Clang Format

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  issue_comment:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: >-
      github.event_name != 'issue_comment'
      || github.event.issue.pull_request != ''
      && github.event.comment.body == 'Do: Run Checks'
      && github.event.comment.user.id == github.event.issue.user.id

    steps:
      - name: Initialize Report
        if: ${{ github.event_name == 'issue_comment' }}
        uses: peter-evans/create-or-update-comment@v1.4.1
        id: report
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ${{ github.event_path }}
            ${{ github.run_id }}
            &#x1F7E1; Rerunning 'Check Clang Format'

      - uses: actions/checkout@v2

      # https://github.com/DoozyX/clang-format-lint-action
      - uses: DoozyX/clang-format-lint-action@v0.5
        with:
          source: '.'
          clangFormatVersion: 9

      - name: Report Success
        if: ${{ github.event_name == 'issue_comment' && success() }}
        uses: peter-evans/create-or-update-comment@v1.4.1
        with:
          comment-id: ${{ steps.report.outputs.comment-id }}
          body: |
            &#x2714; Passed 'Check Clang Format'

      - name: Report Failure
        if: ${{ github.event_name == 'issue_comment' && failure() }}
        uses: peter-evans/create-or-update-comment@v1.4.1
        with:
          comment-id: ${{ steps.report.outputs.comment-id }}
          body: |
            &#x274C; Failed 'Check Clang Format'
