name: Run ClangFormat

on:
  issue_comment:
    types: [ created ]

jobs:
  reformat:
    name: ClangFormat
    if: >-
      github.event.issue.pull_request != ''
      && github.event.comment.body == 'Do: ClangFormat'
      && github.event.comment.user.id == github.event.issue.user.id
    runs-on: ubuntu-latest

    steps:
      - name: Acknowledge
        uses: peter-evans/create-or-update-comment@v1.4.1
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: rocket

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout PR
        uses: dawidd6/action-checkout-pr@v1
        with:
          pr: ${{ github.event.issue.number }}

      - name: Get clang-format
        run: sudo apt-get install clang-format-9

      - name: Clang format each commit in place
        run: |
          git config --local user.email "$(git log -n 1 --pretty=format:'%ae')"
          git config --local user.name 'GitHub Action'
          GIT_EDITOR="sed -iE 's/^pick/edit/g'" git rebase -i $(git merge-base master HEAD)
          set -e
          echo '>>> Beginning Rebasing...'
          while [[ -n $(git status | grep rebase) ]]; do
            find . -name '*.hpp' -o -name '*.cpp' | xargs -L1 clang-format-9 -style=llvm -i --verbose
            echo '>>> Rewriting commit...'
            git add -A
            git commit --amend --no-edit
            echo '>>> Continuing Rebasing...'
            git rebase --continue
          done
          echo '>>> Finished Rebasing!'

      - name: Push
        run: git push --force -v
